AiyBlog/auth.py
import time

from flask import Blueprint,request,session,render_template,redirect,url_for

from AiyBlog import db
from AiyBlog.models import aiyblog_users
from AiyBlog.utils import pwd2hash,authed

auth = Blueprint("auth",__name__,url_prefix='/auth')

@auth.route('/login',methods=["GET","POST"])
def login():

    if authed():
        return redirect(url_for("views.index"))
    if request.method == "POST":
        errors = []
        name = request.form["username"]
        user = aiyblog_users.query.filter_by(name=name).first()


        if user and (request.form["password"])==user.password:
            print('0000')
            session["username"] = user.name
            session["uid"] = user.uid
            session["admin"] = user.group
            user.activated = int(time.time())
            # user.activated = 123
            # print(user.activated)
            db.session.commit()
            db.session.close()

            # login successful
            return redirect(url_for("admin.admin_index"))
        #the user is exists but the password is wrong
        else:

            errors.append("你的用户名或者密码不正确!")
            db.session.close()
            print("11111")
            return render_template("admin/auth/login.html",errors=errors)

    return render_template("admin/auth/login.html")

@auth.route('/register',methods=["GET","POST"])
def register():

    if request.method == "POST":
        errors = []
        username = request.form["username"]
        password = request.form["password"]

        if aiyblog_users.query.filter_by(name=username).first():
            errors.append("用户名已存在!")


        if len(errors)==0:
            u = aiyblog_users(name=username,password=pwd2hash(password.encode("utf-8")),created=int(time.time()))
            db.session.add(u)
            db.session.commit()
            db.session.close()
        else:
            return render_template("admin/auth/register.html",errors=errors)



    return render_template("admin/auth/register.html")


@auth.route('/logout')
def logout():
    if authed():
        session.clear()
        return redirect(url_for("auth.login"))
    else:
        return redirect(url_for("auth.login"))

AiyBlog/views.py
import os

from flask import Blueprint,send_file,safe_join,abort,render_template,session
from flask import current_app as app
from AiyBlog.models import aiyblog_users,aiyblog_options,aiyblog_contents,aiyblog_metas

from sqlalchemy import desc
views = Blueprint("views",__name__)

'''
This is user interface

'''

@views.route('/index')
@views.route('/')
def index():
    """
        index:
        一定数量的文章 10。
        所有独立页面。

    """
    blogs = aiyblog_contents.query.filter_by(type="post").order_by(desc(aiyblog_contents.created)).all()
    pages = aiyblog_contents.query.filter_by(type="page").order_by(aiyblog_contents.order).all()

    new_articles = aiyblog_contents.query.filter_by(type="post").order_by(desc(aiyblog_contents.created)).limit(10).all()

    categories = aiyblog_metas.query.filter_by(type="category").all()

    return render_template('index.html',blogs=blogs,pages=pages,new_articles=new_articles,\
                           categories=categories)



@views.route('/archives/<int:cid>')
def archives(cid):

    blog = aiyblog_contents.query.filter_by(cid=cid).first()
    if blog is None:
        abort(404)
    pages = aiyblog_contents.query.filter_by(type="page").order_by(aiyblog_contents.order).all()
    new_articles = aiyblog_contents.query.filter_by(type="post").order_by(desc(aiyblog_contents.created)).limit(10).all()
    categories = aiyblog_metas.query.filter_by(type="category").all()

    return render_template("post.html",blog=blog,pages=pages,new_articles=new_articles,\
                           categories=categories)

@views.route('/themes/<theme>/static/<path:path>')
def themes_handler(theme, path):
    filename = safe_join(app.root_path, 'themes', theme, 'static', path)
    if os.path.isfile(filename):
        return send_file(filename)
    else:
        abort(404)


@views.route('/index/<path:path>')
def pages_handler(path):
    pages = aiyblog_contents.query.filter_by(type="page").order_by(aiyblog_contents.order).all()
    new_articles = aiyblog_contents.query.filter_by(type="post").order_by(desc(aiyblog_contents.created)).limit(10).all()
    categories = aiyblog_metas.query.filter_by(type="category").all()

    if type(path) == int:
        blog = aiyblog_contents.query.filter_by(cid=path).first()
    else:
        blog = aiyblog_contents.query.filter_by(slug=path).first()

    return render_template("page.html",blog=blog,\
                           pages=pages,categories=categories,new_articles=new_articles)

AiyBlog/themes/default/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% block head %}
    <meta charset="UTF-8">
    <title>{% block title %}{{ get_config("siteName") }}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="stylesheet" href= "{{ request.script_root }}/themes/default/static/grid.css">
    <link rel="stylesheet" href= "{{ request.script_root }}/themes/default/static/normalize.min.css">
    <link rel="stylesheet" href= "{{ request.script_root }}/themes/default/static/style.css">
    {% endblock %}
</head>
<body>
{#header#}
{% block header %}
<header id="header" class="clearfix">
    <div class="container">
        <div class="row">
            <div class="col-mb-12 col-9">
                <a id="logo" href="/">{{ get_config("siteName") }}!</a>
                <p class="description">{{ get_config("siteDescription") }}!</p>
            </div>

            {#这里是全文搜索#}
            <div class="col-3 hidden-tb">
                <form id="search" action="#">
                    <input type="search" class="text" placeholder="输入关键字搜索">
                    <button type="submit" class="submit">搜索</button>
                </form>
            </div>

            {#这里渲染出所有的独立页面#}
            <div id="nav-menu" class="col-mb-12">
                <nav class="clearfix">

                {% if request.path == '/' %}
                 <a class="current" href="/">首页</a>
                {% else %}
                     <a href="/">首页</a>
                {% endif %}
                    {% for page in pages %}
                        <a id="page-{{ page.cid }}" href="/index/{{ page.slug }}">{{ page.title }}</a>

                    {% endfor %}


                </nav>
            </div>
        </div>
    </div>
</header>
{% endblock %}
{#header#}
{#body#}
<div id="body">
    <div class="container">
        <div class="row">
            {#左边文章#}
        {% block content %}
            <div class="col-mb-12 col-8">
            {% for blog in blogs %}
                 <article class="post">
                    <h2 class="post-title"><a href="{{ url_for("views.archives",cid=blog.cid) }}">{{ blog.title }}</a></h2>
                    <ul class="post-meta">
                        <li>
                            作者：<a href="#">{{ get_name_by_id(blog.authorId) }}</a>
                        </li>
                        <li>
                            时间：{{ blog.created|showtime }}
                        </li>
                        <li>
                            分类：<a href="#">{{ get_cgs_by_cid(blog.cid) }}</a>
                        </li>
                        <li>
                            <a href="#">评论</a>
                        </li>
                    </ul>
                    <div class="post-content">
                        {{ blog.text }}
                    </div>
                {% block tags %}
                <p class="tags">标签：none</p>
                {% endblock %}

                </article>
            {% endfor %}

                    {% block comments %}

                    {% endblock %}
            </div>
        {% endblock %}
            {#右边导航内容#}
            {% block rightnav %}
            <div class="col-3 col-offset-1 hidden-tb">
                <section class="sec">
                    <h4>最新文章</h4>
                    <ul>
                        {% for na in new_articles %}
                            <li><a href="{{ url_for("views.archives",cid=na.cid) }}">{{ na.title }}</a></li>
                        {% endfor %}
                    </ul>
                </section>
                <section class="sec">
                    <h4>最新回复</h4>
                    <ul>
                        <li><a href="">无</a></li>
                    </ul>
                </section>
                <section class="sec">
                    <h4>分类</h4>
                    <ul>
                        {% for cat in categories %}
                            <li><a href="/">{{ cat.name }}</a></li>

                        {% endfor %}
                    </ul>
                </section>
                <section class="sec">
                    <h4>其它</h4>
                    <ul>
                        {% if session["uid"] %}
                             <li><a href={{ url_for("admin.admin_index") }}>进入后台({{ get_name_by_id(session["uid"]) }})</a></li>
                        {% else %}
                             <li><a href={{ url_for("auth.login") }}>登录</a></li>
                        {% endif %}

                        <li><a href="{{ url_for("auth.logout") }}">退出</a></li>
                        <li><a href="http://maxlv.org">官方博客</a></li>
                    </ul>
                </section>
            </div>
            {% endblock %}
        </div>
    </div>
</div>
{#body#}

{#footer#}
{% block footer %}
<div id="footer">
&copy2018 <a href="#">{{ get_config("siteName") }}</a> 由 <a href="#">Aiyblog</a> 强力驱动
</div>
{% endblock %}
{#footer#}
</body>
</html>

AiyBlog/themes/default/templates/index.html
{% extends "base.html" %}

{% block title %}
    {{ super() }}
{% endblock %}

{% block head %}
    {{ super() }}
{% endblock %}

{% block content %}
    {{ super() }}
    {% block tags %}
        {% endblock %}
    {% block comments %}

        {% endblock %}
{% endblock %}

{% block rightnav %}
    {{ super() }}
{% endblock %}

{% block footer %}
    {{ super() }}
{% endblock %}

AiyBlog/themes/default/templates/page.html
{% extends "base.html" %}

{% block title %}
    {{ blog.title }}
{% endblock %}

{% block head %}
    {{ super() }}

{% endblock %}



{% block content %}

    <script>
    id = "page-{{ blog.cid }}";
    document.getElementById(id).classList.add("current")
    </script>
                <div class="col-mb-12 col-8">
                     <article class="post">
                        <h2 class="post-title"><a href="{{ url_for("views.archives",cid=blog.cid) }}">{{ blog.title }}</a></h2>
                        <ul class="post-meta">
{#                            <li>#}
{#                                作者：<a href="#">{{ get_name_by_id(blog.authorId) }}</a>#}
{#                            </li>#}
{#                            <li>#}
{#                                时间：{{ blog.created|showtime }}#}
{#                            </li>#}
{#                            <li>#}
{#                                <a href="#">评论</a>#}
{#                            </li>#}
                        </ul>
                        <div class="post-content">
                            {{ blog.text }}
                        </div>
                            {% block tags %}

                            {% endblock %}
                    </article>

                        {% block comments %}
                        <div id="comments">
                        {#这里的评论有三种状态
                        1.用户未登录-->显示原始评论
                        2.用户登录-->显示登录身份并可以直接评论
                        另外：一直都要把已有的评论显示出来
                        #}
                        {#  如果有评论  #}
                        <ol class="comment-list"></ol>

                        <div id="comments-post">
                            <p><strong>添加新评论:</strong></p>
                            <form id="comments-form" action="#">
                            {#    通过session来控制是否显示评论    #}
                                {% if session["uid"] %}
                                <p>
                                    登录身份：<a href="#">admin.</a>
                                    <a href="{{ url_for("auth.logout") }}">退出 >></a>
                                </p>
                                {% endif %}

                                {% if not session["uid"] %}
                                <p>
                                    <label for="author" class="required">称呼</label>
                                    <input type="text" name="author" required>
                                </p>
                                <p>
                                    <label for="email" class="required">Email</label>
                                    <input type="email" name="email" required>
                                </p>
                                <p>
                                    <label for="url">网站</label>
                                    <input type="url" name="url" placeholder="http://">
                                </p>
                                {% endif %}
                                <p>
                                    <label for="content" class="required">内容</label>
                                    <textarea name="content" rows="6" required></textarea>
                                </p>
                                <p>
                                    <button type="submit">提交评论</button>
                                </p>
                            </form>
                        </div>


                        </div>
                        {% endblock %}
            </div>
{% endblock %}





{% block rightnav %}
    {{ super() }}
{% endblock %}

{% block footer %}
    {{ super() }}
{% endblock %}

AiyBlog/themes/default/templates/post.html
{% extends "base.html" %}

{% block title %}
    {{ blog.title }}
{% endblock %}

{% block head %}
    {{ super() }}
{% endblock %}

{% block content %}
                <div class="col-mb-12 col-8">
                     <article class="post">
                        <h2 class="post-title"><a href="{{ url_for("views.archives",cid=blog.cid) }}">{{ blog.title }}</a></h2>
                        <ul class="post-meta">
                            <li>
                                作者：<a href="#">{{ get_name_by_id(blog.authorId) }}</a>
                            </li>
                            <li>
                                时间：{{ blog.created|showtime }}
                            </li>
                            <li>
                                分类：<a href="#">{{ get_cgs_by_cid(blog.cid) }}</a>
                            </li>
                            <li>
                                <a href="#">评论</a>
                            </li>
                        </ul>
                        <div class="post-content">
                            {{ blog.text }}
                        </div>
                            {% block tags %}
                              <p class="tags">标签：none</p>
                            {% endblock %}
                    </article>

                        {% block comments %}
                        <div id="comments">
                        {#这里的评论有三种状态
                        1.用户未登录-->显示原始评论
                        2.用户登录-->显示登录身份并可以直接评论
                        另外：一直都要把已有的评论显示出来
                        #}
                        {#  如果有评论  #}
                        <ol class="comment-list"></ol>

                        <div id="comments-post">
                            <p><strong>添加新评论:</strong></p>
                            <form id="comments-form" action="#">
                            {#    通过session来控制是否显示评论    #}
                                {% if session["uid"] %}
                                <p>
                                    登录身份：<a href="/">{{ session["username"] }}</a>
                                    <a href="{{ url_for("auth.logout") }}">退出 >></a>
                                </p>
                                {% endif %}

                                {% if not session["uid"] %}
                                <p>
                                    <label for="author" class="required">称呼</label>
                                    <input type="text" name="author" required>
                                </p>
                                <p>
                                    <label for="email" class="required">Email</label>
                                    <input type="email" name="email" required>
                                </p>
                                <p>
                                    <label for="url">网站</label>
                                    <input type="url" name="url" placeholder="http://">
                                </p>
                                {% endif %}
                                <p>
                                    <label for="content" class="required">内容</label>
                                    <textarea name="content" rows="6" required></textarea>
                                </p>
                                <p>
                                    <button type="submit">提交评论</button>
                                </p>
                            </form>
                        </div>


                        </div>
                        {% endblock %}
            </div>
{% endblock %}





{% block rightnav %}
    {{ super() }}
{% endblock %}

{% block footer %}
    {{ super() }}
{% endblock %}